### ISSUE TITLE
zadania 1.2.X

### ISSUE THREAD

**Issue by PS164435** [PS164435/PS-wiczenia#1]
zrobiłem zadania 1.2.1 - 1.2.12

**Comment by pjastr** [comment]
@PS164435 proszę o zmianę nazwy repetytorium (obecnie PS ma Pan w nazwie konta - to może zostać, ale proszę o zmianę dla repotytorium). Jeśli chciałby Pan szczegółowe informacje zwrotne, to proszę o zmianę ustawień widoczności na prywatne. Na zajęciach mogę w tym pomóc.
